# Build
FROM docker.io/library/node:20-alpine3.22 AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Serve
FROM docker.io/library/nginx:1.29-alpine3.22

# Para React Router / SPA
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80